SHOW DATABASES;
USE ds_salary;
SHOW TABLES;
DESCRIBE ds_salaries_raw;
ALTER TABLE ds_salaries_raw
ADD employee_residence_full varchar(50);
ALTER TABLE ds_salaries_raw
ADD salary_currency_full varchar(50);
ALTER TABLE ds_salaries_raw
ADD remote_ration_full varchar(50);
UPDATE ds_salaries_raw
SET employee_residence_full = 
    CASE employee_residence 
        WHEN 'ES' THEN 'Spain'
        WHEN 'CA' THEN 'Canada'
        WHEN 'US' THEN 'United States'
        WHEN 'DE' THEN 'Germany'
        WHEN 'GB' THEN 'United Kingdom'
        WHEN 'NG' THEN 'Nigeria'
        WHEN 'IN' THEN 'India'
        WHEN 'HK' THEN 'Hong Kong'
        WHEN 'PT' THEN 'Portugal'
        WHEN 'NL' THEN 'Netherlands'
        WHEN 'CH' THEN 'Switzerland'
        WHEN 'CF' THEN 'Central African Republic'
        WHEN 'FR' THEN 'France'
        WHEN 'AU' THEN 'Australia'
        WHEN 'FI' THEN 'Finland'
        WHEN 'IE' THEN 'Ireland'
        WHEN 'UA' THEN 'Ukraine'
        WHEN 'IL' THEN 'Israel'
        WHEN 'GH' THEN 'Ghana'
        WHEN 'AT' THEN 'Austria'
        WHEN 'CO' THEN 'Colombia'
        WHEN 'SG' THEN 'Singapore'
        WHEN 'SE' THEN 'Sweden'
        WHEN 'SI' THEN 'Slovenia'
        WHEN 'MX' THEN 'Mexico'
        WHEN 'UZ' THEN 'Uzbekistan'
        WHEN 'BR' THEN 'Brazil'
        WHEN 'TH' THEN 'Thailand'
        WHEN 'HR' THEN 'Croatia'
        WHEN 'PL' THEN 'Poland'
        WHEN 'KW' THEN 'Kuwait'
        WHEN 'VN' THEN 'Vietnam'
        WHEN 'CY' THEN 'Cyprus'
        WHEN 'AR' THEN 'Argentina'
        WHEN 'AM' THEN 'Armenia'
        WHEN 'BA' THEN 'Bosnia and Herzegovina'
        WHEN 'KE' THEN 'Kenya'
        WHEN 'GR' THEN 'Greece'
        WHEN 'MK' THEN 'North Macedonia'
        WHEN 'LV' THEN 'Latvia'
        WHEN 'RO' THEN 'Romania'
        WHEN 'PK' THEN 'Pakistan'
        WHEN 'IT' THEN 'Italy'
        WHEN 'MA' THEN 'Morocco'
        WHEN 'LT' THEN 'Lithuania'
        WHEN 'AS' THEN 'American Samoa'
        WHEN 'HU' THEN 'Hungary'
        WHEN 'SK' THEN 'Slovakia'
        WHEN 'CN' THEN 'China'
        WHEN 'CZ' THEN 'Czech Republic'
        WHEN 'CR' THEN 'Costa Rica'
        WHEN 'TR' THEN 'Turkey'
        WHEN 'CL' THEN 'Chile'
        WHEN 'PR' THEN 'Puerto Rico'
        WHEN 'DK' THEN 'Denmark'
        WHEN 'BO' THEN 'Bolivia'
        WHEN 'PH' THEN 'Philippines'
        WHEN 'DO' THEN 'Dominican Republic'
        WHEN 'BE' THEN 'Belgium'
        WHEN 'EG' THEN 'Egypt'
        WHEN 'ID' THEN 'Indonesia'
        WHEN 'AE' THEN 'United Arab Emirates'
        WHEN 'MY' THEN 'Malaysia'
        WHEN 'JP' THEN 'Japan'
        WHEN 'EE' THEN 'Estonia'
        WHEN 'HN' THEN 'Honduras'
        WHEN 'RU' THEN 'Russia'
        WHEN 'DZ' THEN 'Algeria'
        WHEN 'IQ' THEN 'Iraq'
		WHEN 'BG' THEN 'Bulgaria'
		WHEN 'JE' THEN 'Jersey'
    	WHEN 'RS' THEN 'Serbia'
		WHEN 'NZ' THEN 'New Zealand'
    	WHEN 'MD' THEN 'Moldova'
    	WHEN 'LU' THEN 'Luxembourg'
    	WHEN 'MT' THEN 'Malta'
    	ELSE 'Unknown'
        END;
UPDATE ds_salaries_raw
SET salary_currency_full = 
    CASE salary_currency
        WHEN 'EUR' THEN 'Euro'
        WHEN 'USD' THEN 'United States Dollar'
        WHEN 'INR' THEN 'Indian Rupee'
        WHEN 'HKD' THEN 'Hong Kong Dollar'
        WHEN 'CHF' THEN 'Swiss Franc'
        WHEN 'GBP' THEN 'Great British Pound'
        WHEN 'AUD' THEN 'Australian Dollar'
        WHEN 'SGD' THEN 'Singapore Dollar'
        WHEN 'CAD' THEN 'Canadian Dollar'
        WHEN 'ILS' THEN 'Israeli New Shekel'
        WHEN 'BRL' THEN 'Brazilian Real'
        WHEN 'THB' THEN 'Thai Baht'
        WHEN 'PLN' THEN 'Polish Zloty'
        WHEN 'HUF' THEN 'Hungarian Forint'
        WHEN 'CZK' THEN 'Czech Koruna'
        WHEN 'DKK' THEN 'Danish Krone'
        WHEN 'JPY' THEN 'Japanese Yen'
        WHEN 'MXN' THEN 'Mexican Peso'
        WHEN 'TRY' THEN 'Turkish Lira'
        WHEN 'CLP' THEN 'Chilean Peso'
        ELSE 'Unknown'
    END;
UPDATE ds_salaries_raw
SET remote_ration_full = CASE remote_ratio
WHEN 100 THEN 'remote job'
WHEN 50 THEN 'hybrid job'
WHEN 0 THEN 'office job'
ELSE 'office job'
END;